name: prp-accepted-do-explain

on:
  issues:
    types: [labeled]

jobs:
  post-comment:
    if: github.event.label.name == 'PRP:Accepted'
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Post comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_REPO: ${{ github.repository }}
            NUMBER: ${{ github.event.issue.number }}
            BODY: |
                Congratulations, your request has been approved! 🎉

                This means that you can start working on this contribution.

                ❗ Please take a moment to fill the [participation form](https://bughunters.google.com/report/tsunami)
                
                If you are unsure where to start, we have compiled a set of
                useful guides in our documentation:

                📖 https://google.github.io/tsunami-security-scanner/howto/
                
                *Unfortunately, our documentation is not yet complete for
                fingerprints, Python plugins and weak credential detectors. For
                these, we recommend looking at existing plugins.*

                📢 Read latest announcements on [GitHub pages](https://google.github.io/tsunami-security-scanner/)

                *~The Tsunami PRP team*
